### ISSUE TITLE
need help compiling on m1 Mac

### ISSUE THREAD

**Issue by Yoyopizzacat** [shiiion/dolphin#110]
here is the error code

clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Binaries/Dolphin.app/Contents/MacOS/Dolphin] Error 1
make[1]: *** [Source/Core/DolphinQt/CMakeFiles/dolphin-emu.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "../BuildMacOSUniversalBinary.py", line 367, in <module>
    build(conf)
  File "../BuildMacOSUniversalBinary.py", line 298, in build
    subprocess.check_call(["cmake", "--build", ".",
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--parallel', '8']' returned non-zero exit status 2.

**Comment by Yoyopizzacat** [comment]
forgot to pull submodules sorry

**Comment by Yoyopizzacat** [comment]
please help
